kind: Deployment
apiVersion: apps/v1
metadata:
   name: docker-kubernetes
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: docker-kubernetes-app
   template:
      metadata:
        labels:
          app: docker-kubernetes-app
      spec:
       containers:
        - name: docker-kubernetes-container
          image: missthapaliya1/pipeline-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80