kind: Service                             
apiVersion: v1
metadata:
  name: docker-kubernetes
  labels:
    app: docker-kubernetes-app
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: docker-kubernetes-app                    
  type: LoadBalancer                   